Feature/creating components and colors
SlateIn/slatein-app pull request #78
Opened 2020-07-01 21:23 UTC by jayDesai89

2020-07-07 21:07 UTC, Sharmil7171 requested changes
Please make below changes discussed in last Sunday planning meeting
1- we don't require email icon
2- remove underline from Forgot password link
3- add remember me
4- add apple icon in last icon place

2020-07-13 22:56 UTC, jayDesai89 commented
![image](https://user-images.githubusercontent.com/33063944/87361572-8b0ecf00-c53a-11ea-95c1-7c95059eaf6a.png)

2020-07-13 22:56 UTC, jayDesai89 commented
![Capture](https://user-images.githubusercontent.com/33063944/87361604-9e219f00-c53a-11ea-980c-e1538fb4ad8f.PNG)

2020-07-14 01:30 UTC, Sharmil7171 approved these changes

2020-07-14 01:30 UTC, Sharmil7171 approved these changes

2020-07-14 23:39 UTC, tanmay30 approved these changes

2020-07-14 23:44 UTC, merged